title: My Personal Website
description: "This is my awesome personal website."
baseurl: ""  # 设置为 ""，如果你将网站托管在根目录
url: "https://suadwm.github.io"  # 替换为你的实际 GitHub 用户名

plugins:
  - jekyll-mathjax

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
